Employers Data

In [2]:
import numpy as np
import pandas as pd
import os

print(os.getcwd())

d:\Python\TRY

In [3]:
df = pd.read_csv('Employees_raw_Data.csv.csv')
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [4]:
df.head(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes

In [5]:
df.tail(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [7]:
df.size

2464

In [8]:
df.shape

(308, 8)

In [9]:
df.ndim

2

In [10]:
df.describe

<bound method NDFrame.describe of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [11]:
print(df.columns)

Index(['emp_name', 'department', 'join_date', 'salary', 'age',
       'performance_rating', 'city', 'remote_work'],
      dtype='str')

In [12]:
df.dtypes

emp_name                  str
department                str
join_date                 str
salary                float64
age                   float64
performance_rating    float64
city                      str
remote_work               str
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [14]:
df.info

<bound method DataFrame.info of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [15]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [16]:
df.describe()

              salary         age  performance_rating
count     290.000000  298.000000          291.000000
mean    59624.215000   41.600671            3.584192
std     17629.028021   10.800842            1.071073
min      1657.190000   22.000000            1.000000
25%     47116.487500   33.000000            3.000000
50%     59723.160000   42.000000            4.000000
75%     71327.545000   51.000000            4.000000
max    115419.850000   59.000000            5.000000

In [17]:
maxi = df['salary'].max()
print(maxi)

115419.85

In [18]:
average = df['salary'].mean()
print(average)

59624.215000000004

In [19]:
mini = df['salary'].min()
print(mini)

1657.19

In [20]:
avg_age = df['age'].mean()
print(avg_age)

41.600671140939596

In [21]:
perfomance_rating = df['performance_rating'].mean()
print(perfomance_rating)

3.584192439862543

In [22]:
unique_dept = df['department'].unique()
print(unique_dept)

<StringArray>
['Engineering',           nan,          'HR',   'Marketing',       'Sales',
     'Finance',   'MARKETING', 'ENGINEERING',       'SALES']
Length: 9, dtype: str

In [23]:
unique_city = df['city'].unique()
print(unique_city)

<StringArray>
['Pune', 'Delhi', 'Mumbai', 'Chennai', 'Bangalore']
Length: 5, dtype: str

In [24]:
unique_remotework = df['remote_work'].unique()
print(unique_remotework)

<StringArray>
['No', 'yes', 'NO', 'Yes', nan]
Length: 5, dtype: str

In [25]:
df.isna()

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
303,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False
305,False,False,False,True,False,False,False,False
306,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False

In [26]:
#Find missing values in every column
df.isna().sum()

emp_name               0
department            13
join_date              0
salary                18
age                   10
performance_rating    17
city                   0
remote_work           27
dtype: int64

In [27]:
#Which column has most missing values
df.isna().sum().idxmax()

'remote_work'

In [28]:
# How many rows contain at least one missing value?
result = df.isna().any(axis=1).sum()
print(int(result))

74

In [29]:
percentage = (df.isna().any(axis=1).sum() /len(df)) * 100
print(percentage)

24.025974025974026

In [30]:
df.duplicated().sum()

np.int64(8)

In [31]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
303     True
304     True
305     True
306     True
307     True
Length: 308, dtype: bool

In [32]:
#Remove duplicate rows
df = df.drop_duplicates()
print(df)

         emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
295  Employee_296  Engineering  2024-04-30 15:43:57  60865.53  55.0
296  Employee_297        SALES  2024-05-08 11:47:58  64675.01  45.0
297  Employee_298        Sales  2024-05-16 07:51:58  43722.30  56.0
298  Employee_299    Marketing  2024-05-24 03:55:59  71494.66  27.0
299  Employee_300        Sales  2024-06-01 00:00:00  30092.64  40.0

     performance_rating     city remote_work
0                   4.0     Pune          No
1                   3.0    Delhi          No
2                   2.0   Mumbai          No
3                   3.0   Mumbai          No
4                   4.0  Chennai         yes
..                  ...      ...         ...
295                 2.0  Chennai          No
296                 5.0    Delhi          No
297                 5.0     Pune          No
298                 4.0   Mumbai         Yes
299                 4.0     Pune         Yes

[300 rows x 8 columns]

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024-04-30 15:43:57,60865.53,55.0,2.0,Chennai,No
296,Employee_297,SALES,2024-05-08 11:47:58,64675.01,45.0,5.0,Delhi,No
297,Employee_298,Sales,2024-05-16 07:51:58,43722.30,56.0,5.0,Pune,No
298,Employee_299,Marketing,2024-05-24 03:55:59,71494.66,27.0,4.0,Mumbai,Yes
299,Employee_300,Sales,2024-06-01 00:00:00,30092.64,40.0,4.0,Pune,Yes

In [35]:
df['join_date'].dtype

In [36]:
df["join_date"] = pd.to_datetime(df["join_date"])

In [37]:
df["join_date"].dtypes

dtype('<M8[us]')

In [38]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024-04-30 15:43:57,60865.53,55.0,2.0,Chennai,No
296,Employee_297,SALES,2024-05-08 11:47:58,64675.01,45.0,5.0,Delhi,No
297,Employee_298,Sales,2024-05-16 07:51:58,43722.30,56.0,5.0,Pune,No
298,Employee_299,Marketing,2024-05-24 03:55:59,71494.66,27.0,4.0,Mumbai,Yes
299,Employee_300,Sales,2024-06-01 00:00:00,30092.64,40.0,4.0,Pune,Yes

In [39]:
df['month'] = df['join_date'].dt.month

In [40]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No,1
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No,1
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No,1
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No,1
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes,2
...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024-04-30 15:43:57,60865.53,55.0,2.0,Chennai,No,4
296,Employee_297,SALES,2024-05-08 11:47:58,64675.01,45.0,5.0,Delhi,No,5
297,Employee_298,Sales,2024-05-16 07:51:58,43722.30,56.0,5.0,Pune,No,5
298,Employee_299,Marketing,2024-05-24 03:55:59,71494.66,27.0,4.0,Mumbai,Yes,5
299,Employee_300,Sales,2024-06-01 00:00:00,30092.64,40.0,4.0,Pune,Yes,6

In [41]:
df['day'] = df['join_date'].dt.day

In [42]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024-04-30 15:43:57,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024-05-08 11:47:58,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024-05-16 07:51:58,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024-05-24 03:55:59,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024-06-01 00:00:00,30092.64,40.0,4.0,Pune,Yes,6,1

In [43]:
df["join_date"] = df["join_date"].dt.year

In [44]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [45]:
df['remote_work'] = df['remote_work'].str.lower().str.capitalize()

In [46]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [47]:
df['remote_work'].value_counts()

remote_work
No     151
Yes    123
Name: count, dtype: int64

In [48]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [49]:
df[df['department'].isna()]['emp_name']

1        Employee_2
11      Employee_12
34      Employee_35
50      Employee_51
69      Employee_70
139    Employee_140
140    Employee_141
154    Employee_155
226    Employee_227
241    Employee_242
247    Employee_248
248    Employee_249
261    Employee_262
Name: emp_name, dtype: str

In [50]:
#Find employees whose department is missing.
df[df['department'].isna()]['emp_name']

1        Employee_2
11      Employee_12
34      Employee_35
50      Employee_51
69      Employee_70
139    Employee_140
140    Employee_141
154    Employee_155
226    Employee_227
241    Employee_242
247    Employee_248
248    Employee_249
261    Employee_262
Name: emp_name, dtype: str

In [51]:
# Find employees whose department is missing.
df['department'] = df['department'].fillna('Unknown')

In [52]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,Unknown,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [53]:
df['department'].value_counts()

department
Engineering    81
Sales          80
Finance        47
Marketing      43
HR             27
Unknown        13
ENGINEERING     4
SALES           3
MARKETING       2
Name: count, dtype: int64

In [54]:
df[df['salary'].isna()]['salary']

5     NaN
8     NaN
11    NaN
43    NaN
81    NaN
92    NaN
127   NaN
150   NaN
151   NaN
157   NaN
185   NaN
189   NaN
202   NaN
234   NaN
242   NaN
Name: salary, dtype: float64

In [55]:
#Fill the missing values with mean
mean_val = df['salary'].mean()
df['salary'] = df['salary'].fillna(mean_val)

In [56]:
df['salary'].value_counts()

salary
59597.557158    15
60820.290000     1
48271.190000     1
98590.990000     1
71410.540000     1
                ..
60865.530000     1
64675.010000     1
43722.300000     1
71494.660000     1
30092.640000     1
Name: count, Length: 286, dtype: int64

In [57]:
df[df['age'].isna()]['age']

9     NaN
15    NaN
37    NaN
67    NaN
68    NaN
77    NaN
88    NaN
97    NaN
199   NaN
278   NaN
Name: age, dtype: float64

In [58]:
#Fill the null values with median of ages
median_val = df['age'].median()
df['age'] = df['age'].fillna(median_val)

In [59]:
df['age']

0      51.0
1      30.0
2      55.0
3      56.0
4      43.0
       ...
295    55.0
296    45.0
297    56.0
298    27.0
299    40.0
Name: age, Length: 300, dtype: float64

In [60]:
#finding the null values in performance rating
df[df['performance_rating'].isna()]['performance_rating']

35    NaN
36    NaN
38    NaN
51    NaN
75    NaN
77    NaN
123   NaN
155   NaN
161   NaN
195   NaN
202   NaN
227   NaN
234   NaN
249   NaN
275   NaN
292   NaN
Name: performance_rating, dtype: float64

In [61]:
#Remove the rows of performance rating
df = df.dropna()

In [62]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,Unknown,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [63]:
df.isna()

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
295,False,False,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False

In [64]:
df.isna().sum()

emp_name              0
department            0
join_date             0
salary                0
age                   0
performance_rating    0
city                  0
remote_work           0
month                 0
day                   0
dtype: int64

In [65]:
min_salary = df['salary'].min()
print(min_salary)

1657.19

In [66]:
max_salary = df['salary'].max()
print(max_salary)

115419.85

In [67]:
print(df[df['salary'] > 20000]['salary'])

0      60820.29
1      48271.19
2      98590.99
3      71410.54
4      23547.43
         ...
295    60865.53
296    64675.01
297    43722.30
298    71494.66
299    30092.64
Name: salary, Length: 259, dtype: float64

In [68]:
print(df[df['salary'] > 100000]['salary'])

246    115419.85
Name: salary, dtype: float64

In [69]:
print(df['age'].min())

22.0

In [70]:
df.loc[df['age'].idxmin()]

emp_name              Employee_54
department                Finance
join_date                    2019
salary                   24862.42
age                          22.0
performance_rating            4.0
city                        Delhi
remote_work                    No
month                           2
day                            20
Name: 53, dtype: object

In [71]:
print(df['age'].max())

59.0

In [72]:
df.loc[df['age'].idxmax()]

emp_name              Employee_31
department              Marketing
join_date                    2018
salary                    1657.19
age                          59.0
performance_rating            5.0
city                       Mumbai
remote_work                   Yes
month                           8
day                            24
Name: 30, dtype: object

In [73]:
print(df[df['age'] < 60]['emp_name'])

0        Employee_1
1        Employee_2
2        Employee_3
3        Employee_4
4        Employee_5
           ...
295    Employee_296
296    Employee_297
297    Employee_298
298    Employee_299
299    Employee_300
Name: emp_name, Length: 261, dtype: str

In [74]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,2018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,Unknown,2018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,2018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,2024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,2024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,2024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,2024,30092.64,40.0,4.0,Pune,Yes,6,1

In [82]:
print(df[df['department'] == 'Engineering']['emp_name'])

0        Employee_1
16      Employee_17
17      Employee_18
18      Employee_19
19      Employee_20
           ...
286    Employee_287
287    Employee_288
288    Employee_289
293    Employee_294
295    Employee_296
Name: emp_name, Length: 70, dtype: str

In [84]:
print(df[df['salary'] >= 70000]['emp_name'])

2        Employee_3
3        Employee_4
7        Employee_8
16      Employee_17
19      Employee_20
           ...
269    Employee_270
271    Employee_272
287    Employee_288
291    Employee_292
298    Employee_299
Name: emp_name, Length: 70, dtype: str

In [88]:
print(df[(df['salary'] > 70000) & (df['performance_rating'] >= 4.0)]['emp_name'])

7        Employee_8
16      Employee_17
19      Employee_20
20      Employee_21
40      Employee_41
50      Employee_51
55      Employee_56
61      Employee_62
64      Employee_65
67      Employee_68
70      Employee_71
74      Employee_75
79      Employee_80
80      Employee_81
84      Employee_85
89      Employee_90
91      Employee_92
119    Employee_120
120    Employee_121
132    Employee_133
140    Employee_141
142    Employee_143
156    Employee_157
162    Employee_163
167    Employee_168
173    Employee_174
181    Employee_182
184    Employee_185
188    Employee_189
193    Employee_194
201    Employee_202
228    Employee_229
241    Employee_242
244    Employee_245
256    Employee_257
259    Employee_260
271    Employee_272
298    Employee_299
Name: emp_name, dtype: str

In [92]:
print(df[(df['department'] == 'Engineering') | (df['department'] == 'Data Science')]['emp_name'])

0        Employee_1
16      Employee_17
17      Employee_18
18      Employee_19
19      Employee_20
           ...
286    Employee_287
287    Employee_288
288    Employee_289
293    Employee_294
295    Employee_296
Name: emp_name, Length: 70, dtype: str

In [95]:
print(df[(df['age'] > 40) & (df['salary'] > 60000) & (df['performance_rating'] >= 4)][['emp_name','salary']])

         emp_name    salary
0      Employee_1  60820.29
10    Employee_11  69089.77
16    Employee_17  91778.18
20    Employee_21  98198.81
40    Employee_41  80936.95
41    Employee_42  60184.20
44    Employee_45  63583.07
50    Employee_51  88548.30
55    Employee_56  70589.71
61    Employee_62  75292.84
62    Employee_63  66426.28
64    Employee_65  76192.80
67    Employee_68  71333.32
70    Employee_71  73451.28
74    Employee_75  82997.97
80    Employee_81  74857.49
84    Employee_85  72275.15
86    Employee_87  65834.99
88    Employee_89  61745.93
106  Employee_107  67432.77
118  Employee_119  65596.34
119  Employee_120  86556.41
120  Employee_121  75437.87
128  Employee_129  69348.24
132  Employee_133  72422.59
139  Employee_140  68963.97
140  Employee_141  86120.58
142  Employee_143  98757.28
156  Employee_157  77107.63
162  Employee_163  81229.92
173  Employee_174  71211.30
176  Employee_177  62165.32
188  Employee_189  97093.46
221  Employee_222  69072.84
229  Employee_230  60634.74
241  Employee_242  84603.74
244  Employee_245  70378.03
256  Employee_257  90368.55
259  Employee_260  86638.99
260  Employee_261  61392.63
271  Employee_272  70133.45
276  Employee_277  60873.39
278  Employee_279  64868.22
296  Employee_297  64675.01

In [96]:
df.sort_values(by="salary", ascending=False)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
246,Employee_247,Engineering,2023,115419.85,26.0,3.0,Mumbai,Yes,4,12
146,Employee_147,Marketing,2021,99416.45,25.0,2.0,Pune,Yes,2,18
142,Employee_143,ENGINEERING,2021,98757.28,58.0,4.0,Pune,Yes,1,17
2,Employee_3,HR,2018,98590.99,55.0,2.0,Mumbai,No,1,16
52,Employee_53,Finance,2019,98394.60,23.0,2.0,Delhi,No,2,12
...,...,...,...,...,...,...,...,...,...,...
4,Employee_5,Sales,2018,23547.43,43.0,4.0,Chennai,Yes,2,1
199,Employee_200,HR,2022,23293.82,42.0,4.0,Delhi,No,4,9
210,Employee_211,Engineering,2022,22786.04,56.0,5.0,Bangalore,No,7,4
239,Employee_240,Sales,2023,18565.42,26.0,2.0,Chennai,No,2,16
30,Employee_31,Marketing,2018,1657.19,59.0,5.0,Mumbai,Yes,8,24

In [98]:
top_10 = df.sort_values(by="salary" , ascending=False)['emp_name'].head(10)
print(top_10)

246    Employee_247
146    Employee_147
142    Employee_143
2        Employee_3
52      Employee_53
20      Employee_21
91      Employee_92
188    Employee_189
228    Employee_229
269    Employee_270
Name: emp_name, dtype: str

In [101]:
top_10_pr = df.sort_values(by="performance_rating" , ascending=False)['emp_name'].head(10)
print(top_10_pr)

278    Employee_279
266    Employee_267
273    Employee_274
276    Employee_277
258    Employee_259
256    Employee_257
250    Employee_251
252    Employee_253
26      Employee_27
20      Employee_21
Name: emp_name, dtype: str

In [ ]:
#Calculate the average salary by department.
df.groupby("department")["salary"].mean()

"""
df.groupby("department")

This divides the employees into groups based on their department.

For example:

Engineering → employees in Engineering
HR          → employees in HR
Finance     → employees in Finance

Then:

["salary"]

says:

Select the salary column.

Finally:

.mean()
"""

department
ENGINEERING    58955.580000
Engineering    59968.555143
Finance        60368.857892
HR             63571.954627
MARKETING      62526.590000
Marketing      60235.693723
SALES          63623.779053
Sales          56307.869442
Unknown        69120.102263
Name: salary, dtype: float64

In [103]:
#If you want a clean DataFrame
avg_salary = df.groupby("department", as_index=False)["salary"].mean()
print(avg_salary)

    department        salary
0  ENGINEERING  58955.580000
1  Engineering  59968.555143
2      Finance  60368.857892
3           HR  63571.954627
4    MARKETING  62526.590000
5    Marketing  60235.693723
6        SALES  63623.779053
7        Sales  56307.869442
8      Unknown  69120.102263

In [104]:
min_salary = df.groupby("department")["salary"].min()
print(min_salary)

department
ENGINEERING    33934.480000
Engineering    22786.040000
Finance        24862.420000
HR             23293.820000
MARKETING      52778.030000
Marketing       1657.190000
SALES          59597.557158
Sales          18565.420000
Unknown        48271.190000
Name: salary, dtype: float64

In [105]:
max_salary = df.groupby("department")["salary"].max()
print(max_salary)

department
ENGINEERING     98757.28
Engineering    115419.85
Finance         98394.60
HR              98590.99
MARKETING       72275.15
Marketing       99416.45
SALES           66598.77
Sales           87416.23
Unknown         89383.40
Name: salary, dtype: float64

In [107]:
count = df.groupby("department").count()
print(count)

             emp_name  join_date  salary  age  performance_rating  city  \
department
ENGINEERING         4          4       4    4                   4     4
Engineering        70         70      70   70                  70    70
Finance            42         42      42   42                  42    42
HR                 21         21      21   21                  21    21
MARKETING           2          2       2    2                   2     2
Marketing          38         38      38   38                  38    38
SALES               3          3       3    3                   3     3
Sales              69         69      69   69                  69    69
Unknown            12         12      12   12                  12    12

             remote_work  month  day
department
ENGINEERING            4      4    4
Engineering           70     70   70
Finance               42     42   42
HR                    21     21   21
MARKETING              2      2    2
Marketing             38     38   38
SALES                  3      3    3
Sales                 69     69   69
Unknown               12     12   12