Employers Data

In [1]:
import numpy as np
import pandas as pd
import os

print(os.getcwd())

d:\Python\TRY

In [2]:
df = pd.read_csv('Employees_raw_Data.csv.csv')
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [3]:
df.head(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes

In [4]:
df.tail(5)

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [6]:
df.size

2464

In [7]:
df.shape

(308, 8)

In [8]:
df.ndim

2

In [9]:
df.describe

<bound method NDFrame.describe of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [10]:
print(df.columns)

Index(['emp_name', 'department', 'join_date', 'salary', 'age',
       'performance_rating', 'city', 'remote_work'],
      dtype='str')

In [11]:
df.dtypes

emp_name                  str
department                str
join_date                 str
salary                float64
age                   float64
performance_rating    float64
city                      str
remote_work               str
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   emp_name            308 non-null    str
 1   department          295 non-null    str
 2   join_date           308 non-null    str
 3   salary              290 non-null    float64
 4   age                 298 non-null    float64
 5   performance_rating  291 non-null    float64
 6   city                308 non-null    str
 7   remote_work         281 non-null    str
dtypes: float64(3), str(5)
memory usage: 19.4 KB

In [13]:
df.info

<bound method DataFrame.info of          emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
303  Employee_214        Sales  2022-07-28 02:14:51  72054.11  39.0
304  Employee_107  Engineering  2020-04-10 15:05:25  67432.77  46.0
305  Employee_128      Finance  2020-09-22 04:29:42       NaN  29.0
306  Employee_177    Marketing  2021-10-11 03:46:21  62165.32  51.0
307   Employee_74      Finance  2019-07-27 00:52:59  62111.89  30.0

     performance_rating       city remote_work
0                   4.0       Pune          No
1                   3.0      Delhi          No
2                   2.0     Mumbai          No
3                   3.0     Mumbai          No
4                   4.0    Chennai         yes
..                  ...        ...         ...
303                 3.0       Pune          No
304                 4.0  Bangalore         Yes
305                 4.0  Bangalore          No
306                 4.0  Bangalore          NO
307                 2.0  Bangalore         Yes

[308 rows x 8 columns]>

In [14]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
303,Employee_214,Sales,2022-07-28 02:14:51,72054.11,39.0,3.0,Pune,No
304,Employee_107,Engineering,2020-04-10 15:05:25,67432.77,46.0,4.0,Bangalore,Yes
305,Employee_128,Finance,2020-09-22 04:29:42,NaN,29.0,4.0,Bangalore,No
306,Employee_177,Marketing,2021-10-11 03:46:21,62165.32,51.0,4.0,Bangalore,NO
307,Employee_74,Finance,2019-07-27 00:52:59,62111.89,30.0,2.0,Bangalore,Yes

In [15]:
df.describe()

              salary         age  performance_rating
count     290.000000  298.000000          291.000000
mean    59624.215000   41.600671            3.584192
std     17629.028021   10.800842            1.071073
min      1657.190000   22.000000            1.000000
25%     47116.487500   33.000000            3.000000
50%     59723.160000   42.000000            4.000000
75%     71327.545000   51.000000            4.000000
max    115419.850000   59.000000            5.000000

In [16]:
maxi = df['salary'].max()
print(maxi)

115419.85

In [17]:
average = df['salary'].mean()
print(average)

59624.215000000004

In [18]:
mini = df['salary'].min()
print(mini)

1657.19

In [19]:
avg_age = df['age'].mean()
print(avg_age)

41.600671140939596

In [20]:
perfomance_rating = df['performance_rating'].mean()
print(perfomance_rating)

3.584192439862543

In [21]:
unique_dept = df['department'].unique()
print(unique_dept)

<StringArray>
['Engineering',           nan,          'HR',   'Marketing',       'Sales',
     'Finance',   'MARKETING', 'ENGINEERING',       'SALES']
Length: 9, dtype: str

In [22]:
unique_city = df['city'].unique()
print(unique_city)

<StringArray>
['Pune', 'Delhi', 'Mumbai', 'Chennai', 'Bangalore']
Length: 5, dtype: str

In [23]:
unique_remotework = df['remote_work'].unique()
print(unique_remotework)

<StringArray>
['No', 'yes', 'NO', 'Yes', nan]
Length: 5, dtype: str

In [24]:
df.isna()

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
303,False,False,False,False,False,False,False,False
304,False,False,False,False,False,False,False,False
305,False,False,False,True,False,False,False,False
306,False,False,False,False,False,False,False,False
307,False,False,False,False,False,False,False,False

In [25]:
#Find missing values in every column
df.isna().sum()

emp_name               0
department            13
join_date              0
salary                18
age                   10
performance_rating    17
city                   0
remote_work           27
dtype: int64

In [26]:
#Which column has most missing values
df.isna().sum().idxmax()

'remote_work'

In [27]:
# How many rows contain at least one missing value?
result = df.isna().any(axis=1).sum()
print(int(result))

74

In [28]:
percentage = (df.isna().any(axis=1).sum() /len(df)) * 100
print(percentage)

24.025974025974026

In [29]:
df.duplicated().sum()

np.int64(8)

In [30]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
303     True
304     True
305     True
306     True
307     True
Length: 308, dtype: bool

In [31]:
#Remove duplicate rows
df = df.drop_duplicates()
print(df)

         emp_name   department            join_date    salary   age  \
0      Employee_1  Engineering  2018-01-01 00:00:00  60820.29  51.0
1      Employee_2          NaN  2018-01-08 20:04:01  48271.19  30.0
2      Employee_3           HR  2018-01-16 16:08:02  98590.99  55.0
3      Employee_4    Marketing  2018-01-24 12:12:02  71410.54  56.0
4      Employee_5        Sales  2018-02-01 08:16:03  23547.43  43.0
..            ...          ...                  ...       ...   ...
295  Employee_296  Engineering  2024-04-30 15:43:57  60865.53  55.0
296  Employee_297        SALES  2024-05-08 11:47:58  64675.01  45.0
297  Employee_298        Sales  2024-05-16 07:51:58  43722.30  56.0
298  Employee_299    Marketing  2024-05-24 03:55:59  71494.66  27.0
299  Employee_300        Sales  2024-06-01 00:00:00  30092.64  40.0

     performance_rating     city remote_work
0                   4.0     Pune          No
1                   3.0    Delhi          No
2                   2.0   Mumbai          No
3                   3.0   Mumbai          No
4                   4.0  Chennai         yes
..                  ...      ...         ...
295                 2.0  Chennai          No
296                 5.0    Delhi          No
297                 5.0     Pune          No
298                 4.0   Mumbai         Yes
299                 4.0     Pune         Yes

[300 rows x 8 columns]

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work
0,Employee_1,Engineering,2018-01-01 00:00:00,60820.29,51.0,4.0,Pune,No
1,Employee_2,NaN,2018-01-08 20:04:01,48271.19,30.0,3.0,Delhi,No
2,Employee_3,HR,2018-01-16 16:08:02,98590.99,55.0,2.0,Mumbai,No
3,Employee_4,Marketing,2018-01-24 12:12:02,71410.54,56.0,3.0,Mumbai,No
4,Employee_5,Sales,2018-02-01 08:16:03,23547.43,43.0,4.0,Chennai,yes
...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,2024-04-30 15:43:57,60865.53,55.0,2.0,Chennai,No
296,Employee_297,SALES,2024-05-08 11:47:58,64675.01,45.0,5.0,Delhi,No
297,Employee_298,Sales,2024-05-16 07:51:58,43722.30,56.0,5.0,Pune,No
298,Employee_299,Marketing,2024-05-24 03:55:59,71494.66,27.0,4.0,Mumbai,Yes
299,Employee_300,Sales,2024-06-01 00:00:00,30092.64,40.0,4.0,Pune,Yes

In [34]:
df['join_date'].dtype

In [72]:
df["join_date"] = pd.to_datetime(df["join_date"])

In [73]:
df["join_date"].dtypes

dtype('<M8[ns]')

In [75]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970-01-01 00:00:00.000002018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970-01-01 00:00:00.000002018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,1970-01-01 00:00:00.000002018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,1970-01-01 00:00:00.000002018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,1970-01-01 00:00:00.000002018,23547.43,43.0,4.0,Chennai,yes,2,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970-01-01 00:00:00.000002024,60865.53,55.0,2.0,Chennai,No,4,30
296,Employee_297,SALES,1970-01-01 00:00:00.000002024,64675.01,45.0,5.0,Delhi,No,5,8
297,Employee_298,Sales,1970-01-01 00:00:00.000002024,43722.30,56.0,5.0,Pune,No,5,16
298,Employee_299,Marketing,1970-01-01 00:00:00.000002024,71494.66,27.0,4.0,Mumbai,Yes,5,24
299,Employee_300,Sales,1970-01-01 00:00:00.000002024,30092.64,40.0,4.0,Pune,Yes,6,1

In [76]:
df['month'] = df['join_date'].dt.month

In [77]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970-01-01 00:00:00.000002018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970-01-01 00:00:00.000002018,48271.19,30.0,3.0,Delhi,No,1,8
2,Employee_3,HR,1970-01-01 00:00:00.000002018,98590.99,55.0,2.0,Mumbai,No,1,16
3,Employee_4,Marketing,1970-01-01 00:00:00.000002018,71410.54,56.0,3.0,Mumbai,No,1,24
4,Employee_5,Sales,1970-01-01 00:00:00.000002018,23547.43,43.0,4.0,Chennai,yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970-01-01 00:00:00.000002024,60865.53,55.0,2.0,Chennai,No,1,30
296,Employee_297,SALES,1970-01-01 00:00:00.000002024,64675.01,45.0,5.0,Delhi,No,1,8
297,Employee_298,Sales,1970-01-01 00:00:00.000002024,43722.30,56.0,5.0,Pune,No,1,16
298,Employee_299,Marketing,1970-01-01 00:00:00.000002024,71494.66,27.0,4.0,Mumbai,Yes,1,24
299,Employee_300,Sales,1970-01-01 00:00:00.000002024,30092.64,40.0,4.0,Pune,Yes,1,1

In [78]:
df['day'] = df['join_date'].dt.day

In [79]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970-01-01 00:00:00.000002018,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970-01-01 00:00:00.000002018,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970-01-01 00:00:00.000002018,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970-01-01 00:00:00.000002018,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970-01-01 00:00:00.000002018,23547.43,43.0,4.0,Chennai,yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970-01-01 00:00:00.000002024,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970-01-01 00:00:00.000002024,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970-01-01 00:00:00.000002024,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970-01-01 00:00:00.000002024,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970-01-01 00:00:00.000002024,30092.64,40.0,4.0,Pune,Yes,1,1

In [80]:
df["join_date"] = df["join_date"].dt.year

In [82]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970,23547.43,43.0,4.0,Chennai,yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970,30092.64,40.0,4.0,Pune,Yes,1,1

In [84]:
df['remote_work'] = df['remote_work'].str.lower().str.capitalize()

In [86]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970,23547.43,43.0,4.0,Chennai,Yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970,30092.64,40.0,4.0,Pune,Yes,1,1

In [87]:
df['remote_work'].value_counts()

remote_work
No     151
Yes    123
Name: count, dtype: int64

In [88]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,NaN,1970,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970,23547.43,43.0,4.0,Chennai,Yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970,30092.64,40.0,4.0,Pune,Yes,1,1

In [92]:
df[df['department'].isna()]['emp_name']

1        Employee_2
11      Employee_12
34      Employee_35
50      Employee_51
69      Employee_70
139    Employee_140
140    Employee_141
154    Employee_155
226    Employee_227
241    Employee_242
247    Employee_248
248    Employee_249
261    Employee_262
Name: emp_name, dtype: str

In [ ]:
#Find employees whose department is missing.
df[df['department'].isna()]['emp_name']

1        Employee_2
11      Employee_12
34      Employee_35
50      Employee_51
69      Employee_70
139    Employee_140
140    Employee_141
154    Employee_155
226    Employee_227
241    Employee_242
247    Employee_248
248    Employee_249
261    Employee_262
Name: emp_name, dtype: str

In [ ]:
# Find employees whose department is missing.
df['department'] = df['department'].fillna('Unknown')

In [98]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,Unknown,1970,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970,23547.43,43.0,4.0,Chennai,Yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970,30092.64,40.0,4.0,Pune,Yes,1,1

In [100]:
df['department'].value_counts()

department
Engineering    81
Sales          80
Finance        47
Marketing      43
HR             27
Unknown        13
ENGINEERING     4
SALES           3
MARKETING       2
Name: count, dtype: int64

In [102]:
df[df['salary'].isna()]['salary']

5     NaN
8     NaN
11    NaN
43    NaN
81    NaN
92    NaN
127   NaN
150   NaN
151   NaN
157   NaN
185   NaN
189   NaN
202   NaN
234   NaN
242   NaN
Name: salary, dtype: float64

In [106]:
#Fill the missing values with mean
mean_val = df['salary'].mean()
df['salary'] = df['salary'].fillna(mean_val)

In [107]:
df['salary'].value_counts()

salary
59597.557158    15
60820.290000     1
48271.190000     1
98590.990000     1
71410.540000     1
                ..
60865.530000     1
64675.010000     1
43722.300000     1
71494.660000     1
30092.640000     1
Name: count, Length: 286, dtype: int64

In [109]:
df[df['age'].isna()]['age']

9     NaN
15    NaN
37    NaN
67    NaN
68    NaN
77    NaN
88    NaN
97    NaN
199   NaN
278   NaN
Name: age, dtype: float64

In [110]:
#Fill the null values with median of ages
median_val = df['age'].median()
df['age'] = df['age'].fillna(median_val)

In [112]:
df['age']

0      51.0
1      30.0
2      55.0
3      56.0
4      43.0
       ...
295    55.0
296    45.0
297    56.0
298    27.0
299    40.0
Name: age, Length: 300, dtype: float64

In [114]:
#finding the null values in performance rating
df[df['performance_rating'].isna()]['performance_rating']

35    NaN
36    NaN
38    NaN
51    NaN
75    NaN
77    NaN
123   NaN
155   NaN
161   NaN
195   NaN
202   NaN
227   NaN
234   NaN
249   NaN
275   NaN
292   NaN
Name: performance_rating, dtype: float64

In [116]:
#Remove the rows of performance rating
df = df.dropna()

In [117]:
df

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,Employee_1,Engineering,1970,60820.29,51.0,4.0,Pune,No,1,1
1,Employee_2,Unknown,1970,48271.19,30.0,3.0,Delhi,No,1,1
2,Employee_3,HR,1970,98590.99,55.0,2.0,Mumbai,No,1,1
3,Employee_4,Marketing,1970,71410.54,56.0,3.0,Mumbai,No,1,1
4,Employee_5,Sales,1970,23547.43,43.0,4.0,Chennai,Yes,1,1
...,...,...,...,...,...,...,...,...,...,...
295,Employee_296,Engineering,1970,60865.53,55.0,2.0,Chennai,No,1,1
296,Employee_297,SALES,1970,64675.01,45.0,5.0,Delhi,No,1,1
297,Employee_298,Sales,1970,43722.30,56.0,5.0,Pune,No,1,1
298,Employee_299,Marketing,1970,71494.66,27.0,4.0,Mumbai,Yes,1,1
299,Employee_300,Sales,1970,30092.64,40.0,4.0,Pune,Yes,1,1

In [119]:
df.isna()

,emp_name,department,join_date,salary,age,performance_rating,city,remote_work,month,day
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
295,False,False,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False

In [121]:
df.isna().sum()

emp_name              0
department            0
join_date             0
salary                0
age                   0
performance_rating    0
city                  0
remote_work           0
month                 0
day                   0
dtype: int64

In [124]:
min_salary = df['salary'].min()
print(min_salary)

1657.19

In [126]:
max_salary = df['salary'].max()
print(max_salary)

115419.85

In [133]:
print(df[df['salary'] > 20000]['salary'])

0      60820.29
1      48271.19
2      98590.99
3      71410.54
4      23547.43
         ...
295    60865.53
296    64675.01
297    43722.30
298    71494.66
299    30092.64
Name: salary, Length: 259, dtype: float64

In [135]:
print(df[df['salary'] > 100000]['salary'])

246    115419.85
Name: salary, dtype: float64

In [138]:
print(df['age'].min())

22.0

In [140]:
df.loc[df['age'].idxmin()]

emp_name              Employee_54
department                Finance
join_date                    1970
salary                   24862.42
age                          22.0
performance_rating            4.0
city                        Delhi
remote_work                    No
month                           1
day                             1
Name: 53, dtype: object

In [142]:
print(df['age'].max())

59.0

In [144]:
df.loc[df['age'].idxmax()]

emp_name              Employee_31
department              Marketing
join_date                    1970
salary                    1657.19
age                          59.0
performance_rating            5.0
city                       Mumbai
remote_work                   Yes
month                           1
day                             1
Name: 30, dtype: object

In [150]:
print(df[df['age'] < 60]['emp_name'])

0        Employee_1
1        Employee_2
2        Employee_3
3        Employee_4
4        Employee_5
           ...
295    Employee_296
296    Employee_297
297    Employee_298
298    Employee_299
299    Employee_300
Name: emp_name, Length: 261, dtype: str